version: '3.9'
services:
  stats:
    build:
      context: ./stat-service/service
      dockerfile: Dockerfile
    container_name: stats
    ports:
      - "9090:9090"
    depends_on:
      statsdb:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://statsdb:5432/stats
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot

  statsdb:
    image: postgres:14-alpine
    container_name: statsdb
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  ewm:
    build:
      context: ./main-service
      dockerfile: Dockerfile
    container_name: ewm
    ports:
      - "8080:8080"
    depends_on:
      ewmdb:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewmdb:5432/ewm
      - STAT_SERVICE_URL=http://stats:9090
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot

  ewmdb:
    image: postgres:14-alpine
    container_name: ewmdb
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

